# Generated by Django 3.2.9 on 2021-12-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Найменування')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('descriptions', models.TextField(null=True, verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('material', models.CharField(max_length=255, verbose_name='Матеріал')),
                ('color', models.CharField(max_length=255, verbose_name='Колір')),
                ('size', models.CharField(max_length=255, verbose_name='Розмір')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Найменування')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('descriptions', models.TextField(null=True, verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('material', models.CharField(max_length=255, verbose_name='Матеріал')),
                ('color', models.CharField(max_length=255, verbose_name='Колір')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
