# Generated by Django 3.2.9 on 2021-12-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
