# Generated by Django 3.2.9 on 2021-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211209_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самовівиз'), ('delivery', 'Доставка')], default='delivery', max_length=100, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'Замовлення готове'), ('new', 'Нове замовлення'), ('in_progress', 'Замовлення в розробці'), ('completed', 'Замовлення виконано')], default='new', max_length=100, verbose_name='Статус замовлення'),
        ),
    ]
