# Generated by Django 3.2.9 on 2021-12-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211209_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cart', verbose_name='Кошик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('self', 'Самовівиз')], default='delivery', max_length=100, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Замовлення в розробці'), ('new', 'Нове замовлення'), ('completed', 'Замовлення виконано'), ('is_ready', 'Замовлення готове')], default='new', max_length=100, verbose_name='Статус замовлення'),
        ),
    ]
